### ISSUE TITLE
Cannot run the code.

### ISSUE THREAD

**Issue by shanxiaojun** [fengres/mixvoxels#1]
Hello,
I admire your wonderful work, but I get trouble when running the train step. I've done the _Dataset_ step.
(pytorch) PS D:\3d\mixvoxels-main> python train.py --config configs/schedule5000/coffee_martini_5000.txt
Namespace(L1_weight_inital=0.0, L1_weight_rest=0, N_vis=-1, N_voxel_final=262144000, N_voxel_init=16777216, Ortho_weight=0.0, TV_dynamic_factor=3.0, TV_loss_end_iteration=100000, TV_weight_app=1.0, TV_weight_density=1.0, accumulate_decay=0.998, add_timestamp=0, alpha_mask_thre=1e-05, amp=1, basedir='./log', batch_factor=[8.0, 8.0, 2.0, 1.0], batch_size=512, ckpt=None, config='configs/schedule5000/coffee_martini_5000.txt', data_dim_color=27, data_dim_density=27, datadir='D:/3d/mixvoxels-main/data/coffee_martini/', dataset_name='llffvideo', dense_alpha=0, densityMode='None', density_shift=-10, diffuse_kernel=0, distance_scale=25, downsample_test=1.0, downsample_train=2.0, dy_loss='l2', dynamic_granularity='point_wise', dynamic_only_ray_start_iteration=-1, dynamic_pool_kernel_size=41, dynamic_reg_weight=0.1, dynamic_threshold=0.9, dynamic_use_volumetric_render=0, dynamic_weight_decay=0.0, expname=None, export_mesh=0, far=1.0, fea2denseAct='relu', fea_pe=0, featureC=512, featureD=512, filter_loss_weight=0, filter_threshold=1.0, frame_start=0, gamma_end=0.02, gamma_start=0.02, gaussian=0, idx_view=0, init_dynamic_a=-0.1, init_dynamic_b=0.1, init_dynamic_mean=0.0, init_dynamic_std=0.1, init_dynamic_voxel='none', init_static_a=-0.1, init_static_b=0.1, init_static_mean=0.0, init_static_std=0.1, init_static_voxel='none', interpolation='bilinear', lindisp=False, loss_weight_static=1.0, loss_weight_thresh_end=0.0, loss_weight_thresh_start=0.0, lr_basis=0.003, lr_decay_iters=-1, lr_decay_target_ratio=0.1, lr_dynamic_basis=0.003, lr_dynamic_init=0.02, lr_init=0.02, lr_upsample_reset=1, meta_config=None, model_name='TensorVMSplit', nSamples=1000000.0, n_dynamic_iters=2000, n_frame_for_static=2, n_frames=300, n_iters=5000, n_lamb_sh=[48, 12, 12], n_lamb_sh_dynamic=None, n_lamb_sigma=[16, 4, 4], n_lamb_sigma_dynamic=None, n_time_embedding=150, n_train_frames=300, ndc_ray=1, near=0.0, net_layer_add=0, netspec_dy_color='i-d-d-o', netspec_dy_density='i-d-d-o', optimizer='adam', perturb=1.0, point_wise_dynamic_threshold=0.01, pos_pe=6, progress_refresh_rate=10, ray_sampler='simple', ray_sampler_shift=3000, ray_weight_gamma=1, ray_weighted=0, rel_pos_pe=6, remove_foreground=0, render_only=0, render_path=1, render_path_start=0, render_test=1, render_train=0, render_views=120, rgb_diff_log_thresh=0.2, rgb_diff_weight=0.0, rm_weight_mask_thre=0.0001, rm_weight_mask_thre_static=1e-05, scene_box=[-3.0, -3.0, -1.5], shadingMode='MLP_Fea', shift_std=-1, sigma_decay=0.0, sigma_decay_method='l2', sigma_decay_static=0.0, sigma_diff_log_thresh=0.1, sigma_diff_method='log', sigma_diff_weight=0.0, sigma_entropy_weight=0, sigma_entropy_weight_static=0, sigma_static_thresh=0.1, simple_sample_weight=0, simple_sample_weight_end=0, sparsity_lambda=1.0, ssd_dir='./data/llff/fern', static_branch_only_initial=0, static_dynamic_seperate=1, static_featureC=128, static_loss='l2', static_point_detach=1, static_type='mean', step_ratio=4.0, temperature_end=0.2, temperature_start=10.0, temporal_sampler='simple', temporal_sampler_method='mean', temporal_sampler_replace=1, temporal_variance_threshold=0.03, time_head='directdyrender', update_AlphaMask_list=[1750], update_stepratio=None, update_stepratio_iters=None, upsamp_list=[1500, 2000, 2500, 3250], use_cosine_lr_scheduler=1, view_pe=0, vis_every=10000, voxel_init_dynamic=0.1, voxel_init_static=0.1, white_bkgd=False, with_depth=False, zero_dynamic_sigma=1, zero_dynamic_sigma_thresh=1e-05)
Minifying 2 D:/3d/mixvoxels-main/data/coffee_martini/
  File "D:\3d\mixvoxels-main\dataLoader\llff_video.py", line 54, in _minify
    check_output('cp {}/* {}'.format(imgdir_orig, target_img_dir), shell=True)
  File "D:\ide\Anaconda3\envs\pytorch\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "D:\ide\Anaconda3\envs\pytorch\lib\subprocess.py", line 438, in run    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'cp D:/3d/mixvoxels-main/data/coffee_martini/frames\cam00/* D:/3d/mixvoxels-main/data/coffee_martini/frames_2\cam00' returned non-zero exit status 1.

**Comment by fengres** [comment]
Hello, the codes are validated on ubuntu, it seems that you are using windows, the path separator in you system is "\\" while the separator in ubuntu is "/".  Check Line 54 and 64 in llff_video.py 
`check_output('cp {}/* {}'.format(imgdir_orig, target_img_dir), shell=True)`
`check_output('rm {}/*.{}'.format(target_img_dir, ext), shell=True)`
and change the separator '/' into windows version '\'
I hope this will help you.

**Comment by fengres** [comment]
I suggest to run the codes on linux system, due to the cp and rm command maybe different in windows. I can not promise that no other compatibility issues in win system.

**Comment by shanxiaojun** [comment]
Many thanks! I use the code on Linux system and It seems normal. What's more, it runs longer than I expect. It tasks more than two hours on MixVoxels-T using TITAN X GPU.

**Comment by fengres** [comment]
> Many thanks! I use the code on Linux system and It seems normal. What's more, it runs longer than I expect. It tasks more than two hours on MixVoxels-T using TITAN X GPU.

Can you provide the traning log, and the GPU utilization(should be ~70-90%)? In our 3090, the train of coffee-martini is about 16 minutes as shown below. Are the two hours include the dataset pre-processing time(will cost many time in the first traning due to the resizing frames (_minify function) and calculating stds (_calc_std), these time will only be taken in the first running)?
![image](https://user-images.githubusercontent.com/119532200/205565677-7cfabc99-9bdd-4e6a-bd6f-ae1b90ba302c.png)

**Comment by shanxiaojun** [comment]
Sorry, it seems some crash happened to my server and I can't connect to it right now. But I noticed that what took me two hours is the pre-processing time. I feel so grateful to meet a responsible and patient author like you. Again, your work shows amazing results.
