### ISSUE TITLE
oom in dataloarder

### ISSUE THREAD

**Issue by Alex-Zhu1** [fengres/mixvoxels#2]
hello. i try to train wiht coffee_martini， and meet oom in class LLFFVideoDataset(Dataset) : self.read_meta()
my meachine: arm 62GB RTX 3090, and i sure this method kill my train command.
look for your advise! thanks

**Comment by WangFeng18** [comment]
Currently, the codes load all videos into memory, so if your memory is not sufficient (at least 64GB), it will occur oom error. 
If you have no sufficient memory, we recommend to use a larger downscale, by setting downsample_train = 4.0 (while the rendered resolution reduce in half).
