### ISSUE TITLE
Question about table3. 

### ISSUE THREAD

**Issue by johnnylu305** [fengres/mixvoxels#4]
Hi, thank you for the code. I wonder why the psnr (29.26) in this github is slightly lower than the table3 (30.78) in the paper. Do I misunderstand something?

**Comment by WangFeng18** [comment]
Table 3 in our paper is for the mean PSNR over all scenes, we have stated in the caption of Table 3. The 29.26 number you stated refers to the performance of flame_salmon scene with the MixVoxels-T schedule.

**Comment by johnnylu305** [comment]
Thank you for the respond. I want to make sure my understanding is correct. The PSNR of Dy-NeRF and NeRF-T in Table 3 are reported from their paper and they are PSNR of flame_salmon scene according to StreamRF. (https://github.com/AlgoHunt/StreamRF/issues/1) 
![image](https://user-images.githubusercontent.com/22707984/211967951-9c3a9e6d-3118-44aa-aea3-7356210c70f3.png)

**Comment by WangFeng18** [comment]
![image](https://user-images.githubusercontent.com/43294876/211969625-cf063fa7-2e53-49a8-b7fd-d1f5b5bde56b.png)
According to the original paper, we infer that the PSNRs in the DyNeRF is evlauated on all 300 frame videos, I can not find any hints in the original paper that the PSNR number is reported in the flame salmon scene

**Comment by johnnylu305** [comment]
Really thank you for the help. I also check these papers again. I think you are right.

**Comment by johnnylu305** [comment]
I recently revisit this [post](https://github.com/facebookresearch/Neural_3D_Video/issues/18). Perhaps, it is helpful for others.
