### ISSUE TITLE
Question about data processing

### ISSUE THREAD

**Issue by hangg7** [fengres/mixvoxels#6]
Hi Feng! Thanks for releasing your code. I have a quick question about these lines:
https://github.com/fengres/mixvoxels/blob/0013e4ad63c80e5f14eb70383e2b073052d07fba/dataLoader/llff_video.py#L324-L326

I might have missed it, but is there any pointer I can reference to why to drop cam12 for the martini scene? Or is this processing logic specific to your codebase. E.g., seems like hyperreel also attempt to do [something](https://github.com/facebookresearch/hyperreel/blob/ce3e51f8e8527071c5781ad07ada09a4808039fa/datasets/neural_3d.py#L81-L89) quite similar.

**Comment by WangFeng18** [comment]
Hi, we find that the cam 12 of coffee_martini dataset has not been synchronized well to other views, so we delete the view.

**Comment by cucdengjunli** [comment]
mark
