### ISSUE TITLE
How to run DyRender

### ISSUE THREAD

**Issue by seoha-kim** [fengres/mixvoxels#7]
Hello! I read your paper carefully. 
I'm trying to run DyRender using the concat method for time embedding, but I'm getting a memory error. 
It seems like I need to reduce the number of queries from 300 to 50. 
Which part of the code do I need to modify to do this?

**Comment by WangFeng18** [comment]
Sorry for the late reply, if you use the concat method, it is indeed memory-cosuming and you may reduce the query to 50. 
If you hope to run at 300, you may need to decrease the size of batch size.

**Comment by seoha-kim** [comment]
Thank you for your answer. 😀😀

If I want to reduce time query to 50, should I reduce args' n_time_frame to 50? 
Or is there anything else that needs to be revised?

**Comment by WangFeng18** [comment]
If you want to train the whole video of 300 frames, but you just want to sample 50 frames per iteration, you can change the n_frames = 300 and n_train_frames = 50.

If you just want to train 50 frames (e.g., the first 1.67 seconds), you will set n_frames = 50 and n_train_frames = 50.

In our ablations, we choose the first as comparisons, i.e., n_frames = 300 and n_train_frames = 50.

I hope it can help you.
