### ISSUE TITLE
Questions about the dynamic voxel decoupling

### ISSUE THREAD

**Issue by Friedrich-M** [fengres/mixvoxels#8]
First of all, thank you for your outstanding contribution to dynamic rendering. But in the process of running the code, I found that the implementation of the code is different from the method described in the original paper.

Specifically, in the paper, when you decouple the dynamic voxel features, you use an MLP to "increase the feature dimensions for better parsing time - variant density and color", and "use a learnable time - variant latent representation ω to Represent the time query" to get the density or RGB information of the corresponding frame.

<div align="center">
<img width="300" src="https://user-images.githubusercontent.com/85838942/224547606-ac840bd4-bce7-4417-b78c-86c45da30966.png"><img width="400" src="https://user-images.githubusercontent.com/85838942/224547649-f6d37426-8980-4581-9714-f3c24b856267.png">
</div>

However, in your code implementation, the 'DirectDyRender' decouples information directly from the 27-dimensional feature vector without using the method mentioned above.
```python
def forward(self, features, time=None, viewdirs=None, spatio_temporal_sigma_mask=None, temporal_mask=None, temporal_indices=None):
	# spatio_temporal_sigma_mask: for rgb branch prunning
	# temporal_mask is for re-sampling temporal sequence by variance of training pixels.
	Ns = features.shape[0]
	num_frames = self.total_time
	indata = [features, ]
	if self.using_view:
	    indata += [viewdirs,]
	    indata += [positional_encoding(viewdirs, self.viewpe),]
	mlp_in = torch.cat(indata, dim=-1)
	output = self.mlp(mlp_in)
	if temporal_indices is not None and len(temporal_indices.shape) == 1:
	    output = output.reshape(Ns, self.total_time, -1)
	    output = output[:, temporal_indices, :]
	else:
	    output = output.reshape(Ns, num_frames, -1)
	
	if self.using_view:
	    output = torch.sigmoid(output)
	
	output = output.squeeze(dim=-1)
	return output
```

Simultaneously, I noticed that in the implementation of "ForrierDyRender", the $\omega_t$ used by time-query is also not learnable.
```python
self.forrier_basis = np.stack([forrier_basis(T, self.n_time_embedding) for T in range(self.total_time)], axis=1) # (2*n_time_embedding+1, total_time)
self.forrier_basis = torch.from_numpy(self.forrier_basis).to(torch.float16).cuda().detach()
```

I hope you can answer my questions.

**Comment by WangFeng18** [comment]
Thanks for your attention to our work. In implementation, the learnable time queries are implicitly included in the linear layer, because the row of W in the linear layer is actually learnable and act as the time query, we implement it with the linear layer for simplicity.
There indeed a some discrepancy between our codes and the inner-product query, concretely which we implement is inner-product plus a learnable bias, which we find better than only an inner-product query.

I hope it can resolve your problem.
