### ISSUE TITLE
Package Version Error

### ISSUE THREAD

**Issue by oak-barry** [fengres/mixvoxels#9]
Would you mind share all your package and related version? The installation in README is just the same as TensoRF, but not suit for this repo. And I met so many problems caused by package error, like sk-ssim, pyfvvdp, etc. It really takes me a lot time on it, which is so annoying. 
Thank you so much. And by the way, this is absolutely an outstanding work.

**Comment by WangFeng18** [comment]
sorry for the late reply.
The attached file is my pip enviroment, with corresponding versions for each package. Hope it will be helpful for you.
[a.txt](https://github.com/fengres/mixvoxels/files/11208698/a.txt)
